---
- name: Create users
  user: 
    name: carlos
    comment: "Usuario de Carlos Marcelo"
    group: carlos
    append: yes
    groups: sudo,adm,docker

- name: Update SSH keys for users
  authorized_key:
    user: carlos
    state: present
    key: '{{ item }}'
  with_file:
    - keys/carlosm-lacnic2.pub
    - keys/carlosm-lacnic-rsa.pub
    