---
- name: Test hosts for bind9
  ping:
  remote_user: carlos
  tags: dns

- name: Ensure bind9 is installed and updated
  tags: dns
  apt:
    update_cache: yes
    name: bind9
    state: present

- name: Create logging and support directories
  tags: dns
  file:
    name: /var/log/named
    state: directory
    owner: bind
    group: bind
    mode: 0755

- name: Upload config files to master DNS server(s)
  tags: dns, dnsupdate
  copy:
    src: "{{ item }}"
    dest: /etc/bind/
    owner: root
    group: bind
    mode: 0644
  with_fileglob:
    - etc/*

- name: Restart bind9 process
  tags: dns, dnsupdate
  service:
    name: bind9
    state: restarted


#- name: Upload config files to slave DNS server(s)
#  ping:
#  remote_user: carlos
