---
- name: Update users
  hosts: all
  remote_user: carlos
  become: yes
  roles: 
    - usermaint

- name: Update DNS configuration
  hosts: dns-bind9
  remote_user: carlos
  become: yes
  roles:
    - dns-bind9
