---
- name: Create groups
  tags: usermaint
  group:
     name: '{{ item }}'
     state: present
  with_items:
    - docker
    - carlos
    - sudo

- name: Create users
  tags: usermaint
  user: 
    name: carlos
    comment: "Usuario de Carlos Marcelo"
    group: carlos
    append: yes
    groups: sudo,adm,docker

- name: Update SSH keys for users
  tags: usermaint
  authorized_key:
    user: carlos
    state: present
    key: '{{ item }}'
  with_file:
    - keys/carlosm-lacnic2.pub
    - keys/carlosm-lacnic-rsa.pub
    - keys/carlosm-lacnic-ed25519.pub
